### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by ramyakmehra** [neerajsinghsonu/Instagram-Data-Scraper#18]
can u give a propee tutorial so i can also build one of these

**Comment by neerajsinghsonu** [comment]
Hi @Ramya, I think html code, js code and php code would be enough to build new one and all these are already there... Feel free to fork the code :)

**Comment by neerajsinghsonu** [comment]
Hi @harrisonalley ,

Congratulation!! for your journey and Good luck! You can find the some tips on [this website](https://dev.to/asciimoo/how-to-scrape-instagram-profiles-4gm). The author of website has same language (Python) you are thinking to start learning. 

We are using the PHP language to build Instagram data scraper with a very basic tricks.

Get the source code from instagram and extract the JSON data from source.
Parse the JSON and build html view so on.... 

But unfortunately The Social Giant has made some structured changes within their data request and data response. That's why we are developers re thinking and trying to find new way to get data without any API key (By the way it is illegal way). 

Best of luck to you and please do not forget to share your any findings on this.

Best,
Neeraj Singh

**Comment by SoftSandila** [comment]
hi neeraj does this script still works i have deployed on my localhost but it is not working, can u please what do i need to entere in the search bar when i open index.php? thanx

**Comment by neerajsinghsonu** [comment]
Hi @SoftSandila 

Thank you for pointing the issue, The code has been updated and work for hashtag only. Kindly get new zip file and follow the installation instructions. if still, you are facing any issue please let me know.

Best,
Neeraj Singh
