### ISSUE TITLE
How to See the Full Audience Analysis of the Profile

### ISSUE THREAD

**Issue by rajamda** [neerajsinghsonu/Instagram-Data-Scraper#20]
How to know gender, age and location of Instagram profile

Using php or python or in any other language.

(like instagram audience insights )
https://image.ibb.co/nQtNYn/analytics.png

(OR)

https://ibb.co/d9L2Yn

**Comment by neerajsinghsonu** [comment]
Hi @rajamda ,

The Instagram Data Scraper is just a POC model for data scraping. It is not a commercial ready to serve application. Because we are not using a valid Instagram API to get data, hence it can't be a valid commercial product. I am not thinking to make it as commercial for now. But any body can take or inspire by this to build their own road. Please apologizes us for any inconvenience

Thanks :)
