### ISSUE TITLE
UserDetail is Empty

### ISSUE THREAD

**Issue by garry191091** [neerajsinghsonu/Instagram-Data-Scraper#31]
Hello!

The script is amazing it counts well. But i am not getting any user details. the bottom Instagram account details is empty. I am searching followers by #hashtags. If possible how to do so?

Thanks

**Comment by neerajsinghsonu** [comment]
Hello @garry191091,

Thanks for your kind word :) The issue is, this script is no more able to get users detials because of Instagram API changes. I am trying to fix the issue and also trying to recreate/reframe this script as per new Instagram API changes. I will update you and to all users who are seeking to get users details.

Thank you so much!
Neeraj Singh

**Comment by neerajsinghsonu** [comment]
Hello @garry191091 

@account search is now available.
