### ISSUE TITLE
Using App as an API

### ISSUE THREAD

**Issue by TriptonPt** [neerajsinghsonu/Instagram-Data-Scraper#34]
Hello, 

Currently looking for a scraping solution to integrate together with another app and your scraper looks great for my purposes .

Was wondering if it could be used as an API to return results of JSON data in a valid text format and if it supports using proxies .

Thanks !

**Comment by neerajsinghsonu** [comment]
Hello @TriptonPt ,

Script is puerly based on PHP and you can download and update source code as per your need. I would suggest try once and make your awesome API driven script. You can check the documents and comments to understand the existing flow.

Also I must say, go with Instagram API authorizeation so that you will not need to maintain the code frequently. Build an Instagram app, ask permissions and review... & you will be good to go.

Cheers & Best of luck!!
