### ISSUE TITLE
Dont work....

### ISSUE THREAD

**Issue by zaivst** [neerajsinghsonu/Instagram-Data-Scraper#36]
See the screnshot https://s.mail.ru/86Gh/ro9JBwUaj

**Comment by neerajsinghsonu** [comment]
Hello @zaivst ,

Request you to specify the proper error, the shared screeshot has nothing to show. Kindly let me know what is not working #tag search or @ccount search. Please share the error details and full screen so that I can help you and assist you better.

To search @account information you have to set the SESSION ID (click Set Session button).
To search #hashtag nothing special its working fine.

Regards,
Neeraj Singh
